coverage:
  precision: 2
  round: down
  range: "75...85"
  status:
    project: no
    patch: yes
    changes: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
