sentry:
  dsn: "{SENTRY_DSN}"
  release:
    name: "{SENTRY_RELEASE_NAME}"
# This one is optional ... only if you want to use ai-story command
openAi:
  token: ...
amqp:
  url: "{AMQP_URL}"
discord:
    token: "{TOKEN}"
deploy:
  port: "{PORT}"