version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
        - 5672:5672
        - 15673:15672
    networks:
        - ai-art
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - database
    ports:
      - 27017:27017
  mongo-express:
    depends_on:
      mongodb:
        condition: service_started
    
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
    networks:
      - database
  discord-chat-bot:
    depends_on: 
      rabbitmq:
        condition: service_healthy
    build:
      context: ../../
      dockerfile: ./docker/deploy/Dockerfile
      args:
        - DISCORD_TOKEN=$TOKEN
        - OPEN_AI_TOKEN="none"
    networks:
      - ai-art

networks:
  ai-art:
  database: