name: Docker CI

on:
  release:
    types:
      - published
  workflow_dispatch:
  

jobs:
  release-sentry:
    name: Release sentry
    needs: build-and-push-to-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production

  set-up-heroku-deploy:
    name: Set up heroku deploy
    runs-on: ubuntu-latest
    needs:
      build-and-push-to-ghcr
    steps:
      - name: Get all heroku instances
        id: get-instances
        run: echo "::set-output name=matrix::$( fromJson(${{ secrets.HEROKU_INSTANCES_CONFIG_JSON }}) )"
    outputs:
      matrix: ${{ steps.get-instances.outputs.matrix }}
  
  deploy-to-heroku:
      name: Deploy to heroku
      needs: set-up-heroku-deploy
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          conf: ${{ fromJson(needs.set-up-heroku-deploy.outputs.matrix) }}
      steps:
        - name: Tag image
          run: docker tag ghcr.io/karafra/ai-art:latest ${{ matrix.conf.containerUrl }}
        - name: Push to heroku container registry
          run: docker push ${{ matrix.conf.containerUrl }}
        - name: Release
          run: heroku container:release worker -a ${{ matrix.conf.applicationName }}

  build-and-push-to-ghcr:
    name: Build and push Docker image to GitHub Container registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker Image
      env:
        SENTRY_RELEASE_NAME: ${{ github.sha }}
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/build/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} , ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        build-args: |
          ENVIRONMENT=production

  update-heroku-button-config:
   name: Update heroku button config
   needs:
    - deploy-to-heroku
    - release-sentry
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Update app.json sentry release name
      uses: jossef/action-set-json-field@v2
      with:
        file: app.json
        field: env.SENTRY_RELEASE_NAME.value
        value: ${{ github.sha }}
    - name: Push updated files to github
      run: |
        git config --global user.name 'karafra'
        git config --global user.email 'karafra@users.noreply.github.com'
        git commit -am ":bookmark Update sentry release name"
        git push
      
